[workspace]
resolver = "3"
members = [
    "sbsp_backend",
    "sbsp_license",
    "sbsp_tauri",
    "sbsp_remote",
]

[workspace.package]
authors = ["Keinsleif"]
version = "1.0.0"
edition = "2024"
license = "Elastic-2.0"
publish = false

[profile.dev.package.kira]
opt-level = 3

[profile.dev.package.cpal]
opt-level = 3

[profile.dev.package.symphonia]
opt-level = 3

[profile.dev.package.symphonia-core]
opt-level = 3

[profile.dev.package.symphonia-metadata]
opt-level = 3

[profile.dev.package.symphonia-format-riff]
opt-level = 3

[profile.dev.package.symphonia-format-caf]
opt-level = 3

[profile.dev.package.symphonia-format-isomp4]
opt-level = 3

[profile.dev.package.symphonia-format-mkv]
opt-level = 3

[profile.dev.package.symphonia-format-ogg]
opt-level = 3

[profile.dev.package.symphonia-codec-aac]
opt-level = 3

[profile.dev.package.symphonia-codec-adpcm]
opt-level = 3

[profile.dev.package.symphonia-codec-alac]
opt-level = 3

[profile.dev.package.symphonia-bundle-flac]
opt-level = 3

[profile.dev.package.symphonia-bundle-mp3]
opt-level = 3

[profile.dev.package.symphonia-codec-pcm]
opt-level = 3

[profile.dev.package.symphonia-codec-vorbis]
opt-level = 3
