name: 'deploy-update'

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Target Release Tag'
        required: true
        type: string
        default: 'sbsp-v1.2.1'

jobs:
  upload:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: mkdir upload

      - name: 'update latest.json'
        run: gh release download ${{ github.event.inputs.tag_name || github.event.release.tag_name }} -p latest.json -O upload/latest-${{ contains(github.event.inputs.tag_name || github.event.release.tag_name, 'remote') && 'remote' || 'main' }}.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !(github.event.release.prerelease || github.event.release.draft) }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./upload
          destination_dir: update
          keep_files: true
        if: ${{ !(github.event.release.prerelease || github.event.release.draft) }}
