name: 'update-publish'

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: update-publish
  cancel-in-progress: true

jobs:
  publish-latest:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: mkdir upload

      - name: 'update latest.json'
        run: gh release download ${{ github.event.release.tag_name }} -p latest.json -O upload/latest-${{ contains(github.event.release.tag_name, 'remote') && 'remote' || 'main' }}.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./upload
          destination_dir: update
          keep_files: true
